### PR TITLE
reve-de-dragon support all types of actors

### PR DESCRIPTION
**Pull request by VincentVk9373**
Support 'vehicule' which do not have health
Adjust the different fractions (not almost dead if tired, ...)

### CODE REVIEW

**Comment by mclemente** [comment]
Do Entité de Cauchemar have any hp? Because they're returning Dead, since they don't have any Vie.  
Also, there's a way to set up so vehicles don't return anything instead of being always healthy.

**Comment by mclemente** [comment]
Check if my changes are correct.

- Uses the Clamped function (same as before, but it uses a Foundry function instead).
- Entités should now use Endurance as hp (0 = dead).  
- Vehicles are ignored completely.

**Comment by mclemente** [comment]
> Do you have a doc page/pointer about how to use different sets of states? It might be interesting for vehicles, but maybe even for characters who can be tired/weak without being wounded.

It isn't well documented, you would need to add this:
```js
import { descriptions, t } from "../utils.js";

const settings = () => {
	return {
		"starfinder.useThreshold": {
			type: Boolean,
			default: false,
		},
		"starfinder.thresholdNames": {
			type: String,
			default: t("starfinder.thresholdNames.default").join(", "),
		},
		"starfinder.vehicleNames": {
			type: String,
			default: t("starfinder.vehicleNames.default").join(", "),
		},
	};
};
```
And replace the export with this:

```js
export { fraction, breakCondition, descriptions, settings };
```

If `useThreshold` is off, it uses `vehicleNames`. If you only plan to use thresholds, this could be used instead:

```js
import { descriptions, t } from "../utils.js";

const settings = () => {
	return {
		"starfinder.useThreshold": {
			type: Boolean,
			default: true,
			config: false
		},
		"starfinder.thresholdNames": {
			type: String,
			default: t("starfinder.thresholdNames.default").join(", "),
		},
	};
};
```

Also, if you want to setup your own localization instead of using Starfinder's, just make your own `default` and replace it on the object: https://github.com/mclemente/healthEstimate/blob/master/lang/en.json#L155-L174

**Comment by VincentVk9373** [comment]
I should probably have a closer look at blades-in-the-dark / scum-and-villainy to manage the wounds system, it seems close to what the system has (wounds gravity that add up).

**Comment by mclemente** [comment]
> 
> 
> I should probably have a closer look at blades-in-the-dark / scum-and-villainy to manage the wounds system, it seems close to what the system has (wounds gravity that add up).

BitD/S&V have a system with 3 Light injuries, 2 medium injuries and 1 heavy injury. Once you get 3 light injuries, you start getting medium ones.
Does RDD works like that too or can you get Grave injuries without Light injuries? Because if works like that, it's just a matter of summing them and returning `1 - (sum/maxTotal)`.

**Comment by VincentVk9373** [comment]
On RDD, you can get 5 light wounds, 2 serious wounds, one critical.
You can get a serious wound without prior light wounds.
When you have 5 light wounds, next one is automatically serious.
When you have 2 serious wounds, next one is critical.
When you have a critical wound, next one you are dead (and anyway, you might die without other wounds)

**Comment by mclemente** [comment]
Hm, I don't think changing how it works will do anything, maybe changing the numbers further so the colors/states are better distributed, e.g.:
```js
const tableBlessure = {
  legere: [0, 10, 20, 30, 40, 50],
  grave: [0, 65, 80],
  critique: [0, 95],
  inconscient: 100
}
```

**Pull request merged**
